name: Playwright Tests
on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test tags (comma-separated)'
        required: true
        default: 'squad1,vet'
      project:
        description: 'Project to run tests'
        required: true
        default: 'squad1'
      ENV:
        description: 'Test environment'
        required: true
        default: 'STAGING'
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    # - name: Install Playwright Browsers
    #   run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: |
          TAGS="${{ inputs.tags }}"
          PROJECT="${{ inputs.project }}"
          FORMATTED_TAGS=$(echo "$TAGS" | sed 's/,/|/g')  # Convert comma-separated values to regex format
          echo "Running tests with tags: $FORMATTED_TAGS on project: $PROJECT"
          npx playwright test --grep "($FORMATTED_TAGS)" --project=$PROJECT
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
